/**
 * The one definition of what a contextual mark looks like in paragraph HTML.
 *
 * Four things read these marks — the migration, the player's popover, the render
 * pass that strips dangling ones, and the workspace's usage count — and a second
 * opinion about the markup would show up as a mark that one of them cannot see.
 *
 * Regex rather than DOMParser, for the same reason `stripHtml` gives: this runs in
 * tests under the node environment, the markup is generated by our own editor, and
 * reserialising a document through `innerHTML` would silently normalise prose the
 * caller never asked to touch.
 */
export const CONTEXT_MARK_CLASS = 'contextual-text-mark';
export const CONTEXT_ID_ATTR = 'data-context-id';

/** A whole mark: the opening tag, the marked words, the closing tag. */
const MARK = /<span\b([^>]*\bdata-context-id="([^"]*)"[^>]*)>([\s\S]*?)<\/span>/g;

export interface MarkOccurrence {
  entryId: string;
  /** The marked words, with any nested markup left as written. */
  inner: string;
}

/** Every entry id referenced by this paragraph, in the order they appear. */
export const contextIdsIn = (html: string): string[] => {
  const ids: string[] = [];
  for (const match of html.matchAll(MARK)) ids.push(match[2]);
  return ids;
};

export const marksIn = (html: string): MarkOccurrence[] => {
  const marks: MarkOccurrence[] = [];
  for (const match of html.matchAll(MARK)) marks.push({ entryId: match[2], inner: match[3] });
  return marks;
};

/**
 * Replaces marks whose entry no longer exists with the words they wrapped.
 *
 * A reader should never meet a mark that does nothing: the phrase stays in the
 * sentence and reads as ordinary prose. Story Health reports the loss, so it is
 * visible to the author rather than only to the reader.
 */
export const stripUnresolvedMarks = (html: string, exists: (entryId: string) => boolean): string =>
  html.replace(MARK, (whole, _attrs: string, entryId: string, inner: string) =>
    exists(entryId) ? whole : inner
  );

/** The mark as the editor and the migration both write it. */
export const renderContextualMark = (entryId: string, inner: string): string =>
  `<span class="${CONTEXT_MARK_CLASS}" ${CONTEXT_ID_ATTR}="${entryId}">${inner}</span>`;
