const HTML_TAG = /<[^>]*>/g;
const WHITESPACE = /\s+/g;

const ENTITIES: [RegExp, string][] = [
  [/&nbsp;/g, ' '],
  [/&lt;/g, '<'],
  [/&gt;/g, '>'],
  [/&quot;/g, '"'],
  [/&#0?39;/g, "'"],
  [/&apos;/g, "'"],
  // Ampersand last, so an already-decoded "&lt;" is not re-decoded.
  [/&amp;/g, '&'],
];

/**
 * Reduces paragraph HTML to the prose a reader would see.
 *
 * Paragraph text is TipTap output — `<p>`, `<strong>`, `<em>`, and contextual
 * marks like `<span class="contextual-text-mark" data-context="…">phrase</span>`.
 * Dropping tags keeps the marked phrase (it is visible prose) and discards the
 * hover text in `data-context`, which belongs to the Contextual Text explorer
 * rather than to page search.
 *
 * `{{playerName}}` tokens are deliberately left as written, so searching for a
 * variable name finds the paragraphs that print it.
 *
 * Regex rather than DOMParser: this runs in tests under the node environment,
 * and the input is generated by our own editor, not arbitrary pasted markup.
 */
export const stripHtml = (html: string): string => {
  let text = html.replace(HTML_TAG, ' ');
  for (const [pattern, replacement] of ENTITIES) {
    text = text.replace(pattern, replacement);
  }
  return text.replace(WHITESPACE, ' ').trim();
};
